app:
  image: kkarczmarczyk/node-yarn:latest
  volumes:
    - .:/project
    - ~/.yarn:/home/node/.cache/yarn
  working_dir: /project
  expose:
    - "80"
  environment:
    VIRTUAL_HOST: ma-cave.test
    VIRTUAL_PORT: 80
  entrypoint: yarn
  command: start
